### ISSUE TITLE
Distribute in JupyterLite by default

### ISSUE THREAD

**Issue by jtpio** [jtpio/nano-console#20]
Eventually this minimal REPL should be one of the apps distributed by default in JupyterLite.

For now lite ships `lab` and `retro` by default: https://jupyterlite.readthedocs.io/en/latest/api/py/jupyterlite.html#jupyterlite.constants.JUPYTERLITE_APPS

There could be a new app called `cell`.

If this is a standalone app like retro, the look and UX could be different and not limited to the JupyterLab code console.

We'll want to fix https://github.com/jupyterlite/jupyterlite/issues/118 first though.

The `cell` app could be either in core, or as a third-party app under the `jupyterlite` org. The latter might require some work in the `jupyterlite` CLI to allow apps as (federated) plugins.

Related to https://github.com/jupyterlite/jupyterlite/issues/148

**Comment by bollwyvl** [comment]
:+1: to moving this into core when you feel like it's ready, given the deduplication caveats. Perhaps a friendly "budget" on how much this is allowed to increase the final wheel size?
