### ISSUE TITLE
Add a postMessage API

### ISSUE THREAD

**Issue by bollwyvl** [jtpio/nano-console#23]
### Problem

The URL api is robust for one-off solutions, but makes it harder to integrate.

### Proposed Solution

In addition to a well-documented URL param scheme, offer a [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) API that allows for basic things like "run some code", arbitrary lumino commands, or anything that an extender can imagine.

### Background

Having fought with more than a few IFrames, it can be nice to offer both a bare-minimum, fire-and-mostly-forget URL api, as well as a well-structured, message-based API.  A good (counter-)example is the [drawio embed mode](https://www.diagrams.net/doc/faq/embed-mode):

- hooray! it can do lots of things!
- boo! that's pretty much it for docs!
  - a robust API in a JSON schema and typings would go a _long_ way to helping implementers who wanted to build e.g. `replite-react` or `replite-vue` or whatever they want
    - indeed, as a low-effort integrator demo, it could use rjsf to draw a message builder/viewer

### Why both?

By splitting "long term" URL params and "on-demand" `postMessage` an integrator can then get interesting interplay effects: pass `?ui=0&input=0` and then have the host take over firing all of the `execute` methods with their own buttons

For e.g. wasm-based kernels, until we can figure out a [SharedWorker](https://github.com/GoogleChromeLabs/comlink#sharedworker) [worker kernels](https://github.com/jupyterlite/jupyterlite/issues/463) it's particularly important to not add 10s of 100mb kernels, even if in iframes.  In a long-form document, a more feasible approach one would be to have a single iframe/kernel/cell, fixed in the viewport, that gets updated as the reader scrolls/clicks on things.

### Design Considerations

As for what actually goes in this API: a really quick win is the `app.commands.execute`... while no [a-priori schema exists](https://github.com/jupyterlab/lumino/issues/58), a running lab _could_ at least enumerate what commands it has.

**Comment by jtpio** [comment]
@meeseeksdev please migrate to jupyterlite/jupyterlite

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlite/jupyterlite/issues/510
