### ISSUE TITLE
Add buttons to the toolbar

### ISSUE THREAD

**Issue by jtpio** [jtpio/nano-console#8]
Right now the console toolbar is empty:

![image](https://user-images.githubusercontent.com/591645/152142298-c76870ed-ca90-4ec3-8953-cf3717e8a09f.png)

Maybe we should add a couple of buttons to it, for example:

- run
- restart
- clear

**Comment by martinRenou** [comment]
It would be nice if the toolbar was optional, to reduce the space taken by replite if needed

**Comment by jtpio** [comment]
Then it could be an opt-in via a query string parameter?

**Comment by martinRenou** [comment]
That would be great!
